#!/usr/bin/bash

#################################################
# Installer script for RubyOnRails
#
# This script was tested with Ubuntu 10.04 TLS.
#
# Author  : Takahiro Fujiwara ( tfmagician )
# Created : 2010-12-05
# Updated : 2010-12-05
#################################################

# Check executable user.
if [ "${whoami}" != "root" ]; then
echo "You need to be root to run this!"
  exit 2
fi

##
echo 'Install Ruby and some libraries.'
apt-get install -y ruby1.8 libbluecloth-ruby libopenssl-ruby1.8 ruby1.8-dev ri rdoc irb
ln -s /usr/bin/ruby1.8 /usr/bin/ruby

cd ~/
mkdir src
cd src
wget http://rubyforge.org/frs/download.php/69365/rubygems-1.3.6.tgz
tar xvzf rubygems-1.3.6.tgz
cd rubygems-1.3.6
ruby setup.rb
ln -s /usr/bin/gem1.8 /usr/bin/gem

apt-get install -y libonig-dev libyaml-dev geoip-bin libgeoip-dev libgeoip1

apt-get install -y imagemagick libmagickwand-dev
gem install --no-ri --no-rdoc rmagick mysql

##
echo 'Install RubyOnRails and some libraries.'
gem install --no-ri --no-rdoc rails mongrel mime-types textpow chronic ruby-hmac daemons mime-types oniguruma textpow chronic BlueCloth ruby-yadis ruby-openid geoip rspec rspec-rails RedCloth echoe
gem install --no-ri --no-rdoc --version="1.0.1" rack
gem uninstall i18n
